<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aktivasi myIndihomeMasukkan 4 digit kod_49be94</name>
   <tag></tag>
   <elementGuidId>e86d22ca-a8e8-4a49-8b78-22dfc42a192b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#root > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aktivasi myIndihomeMasukkan 4 digit kode verifikasi yang telah Kami kirim ke nomor SMS ••••••••1895Kode yang dimasukkan salah, Anda memiliki 3 kesempatanKirim ulang kode dalam02:42Kirim ulang kode verifikasi       Error  Silakan periksa koneksi internet Anda   Biaya tambahan sebesar Rp200.000 akan dibebankan pada tagihan Anda berikutnya.Terima kasih atas tanggapan Anda!Nomor ponsel Anda telah berhasil diubah!Email Anda telah berhasil diubah!</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
   </webElementXpaths>
</WebElementEntity>
