<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PilihAMBULUAMPELGADINGARJASAASEMBAGU_dc6aa1</name>
   <tag></tag>
   <elementGuidId>5b6e4910-6ab0-4660-8ec0-6077b7072ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select is-invalid form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PilihAMBULUAMPELGADINGARJASAASEMBAGUSBABADBALONG PANGGANGBALUNGBANCARBANGILBANGKALANBANTURBANYUWANGIBATUBAWEANBENCULUKBENJENGBESUKIBINANGUNBLITARBOJONEGOROBONDOWOSOBRONDONGCAMPUR DARATCARUBANCERMEDAMPITDONOMULYODUDUK SAMPEYANDURENANGEMPOLGENDINGGENTENGGLAGAHGLENMOREGONDANGGONDANG WETANGONDANGLEGIGORANG GARENGGRATIGRESIKGURAHJATIROGOJATIROTOJEMBERJENANGANJENGGAWAHJOGOROGOJOMBANGKALIBARUKALIDAWIRKALISATKALITIDUKARANG PLOSOKEDAMEANKEDIRIKENCONGKEPANJENKEREKKERTOSONOKESAMBENKLAKAHKRAKSAANLAMONGANLAWANGLECESLODOYOLUMAJANGMADIUNMAGETANMALANGMAOSPATIMENGANTIMERAK URAKMLANDINGANMOJOKERTOMUNCARNGADILUWIHNGANJUKNGANTANGNGAWINGUNUTNONGKOJAJARPACITANPADANGANPAGAKPAITONPAMEKASANPANATARANPANDAANPAPARPAREPASIRIANPASURUANPESANGGARANPONOROGOPRAJEKANPRAMBONPRIGENPRIGIPROBOLINGGOPUGERPULUNGPUNUNGRAMBIPUJIRENGELROGOJAMPISAMBITSAMPANGSARANGANSEMPOLANSENDUROSIDAYUSINGOSARISITUBONDOSLAHUNGSRENGATSUKAPURASUKODADISUKOSARISUKOWONOSUMBEREJOSUMBERMANJING WETANSUMBERPUCUNGSUMENEPSUMOROTOTANGGULTANJUNG AWAR AWARTONGASTOSARITRENGGALEKTUBANTULUNG AGUNGTUMPANGTURENUTERANWALIKUKUNWANGKALWARUJAYENGWLINGIWONGSOREJOYOSOWILANGUN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='city']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/section[2]/form/div[2]/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROVINSI'])[1]/following::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Kota'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KECAMATAN'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
   </webElementXpaths>
</WebElementEntity>
