<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PilihABIMANYUAGUS SALIMASURANSI BUMI_03295e</name>
   <tag></tag>
   <elementGuidId>922aea04-f9ec-446a-89aa-77a6d170edde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#street</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='street']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>street</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select is-invalid form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PilihABIMANYUAGUS SALIMASURANSI BUMI PUTERAASURANSI JIWA SRAYABALIBALI 1BALI 10BALI 11BALI 12BALI 13BALI 14BALI 16BALI 2BALI 3BALI 4BALI 5BALI 6BALI 7BALI 8BALI 9BALI Gg GAPUROBALI RT36/07BANK BUMI DAYABANK PEMBANGUNAN DAERAHBAWEANBEA DAN CUKAIBIDANBINA REMAJABOLODEWOBULU GANG 1BUNTU KARTOHARJOCOKROAMINOTODALAM STADION WILISDARMA MULYADIPONEGORODPRD KODYADR CIPTODR SUTOMODR SUTOMO 1FLAMBOYAN RT13/RW02FLORESFLORES 1FLORES GANG KERETAFLORES RT34/05GEMOGUNAHALMAHERAHALMAHERA 1HALMAHERA 10HALMAHERA 11HALMAHERA 12HALMAHERA 13HALMAHERA 2HALMAHERA 3HALMAHERA 4HALMAHERA 5HALMAHERA 6HALMAHERA 7HALMAHERA 8HALMAHERA 9HALMAHERA GG SDHIRJANIMAM BONJOLIRIAN BARATJAHITANJAWAJAWA 1JAWA 2JAWA 3JAWA 4JAYENGANJEND SUDIRMANJEND SUDIRMAN 1JENDRAL SUDIRMANKABUPATENKALIMANTANKALIMANTAN 1KALIMANTAN 2KALIMANTAN 4KALIMANTAN 5KALIMANTAN 6KALIMANTAN GG SUMBER UMISKANTOR BP7KANTOR DEPNAKERKANTOR PDAMKANTOR PT TELKOMKAPENDA KODYAKARTOHARJO INDAH BLK OKARTOHARJO INDAH BLOK YKARTOHARJO RT37/05KARTOHARJO RT47/05KARTOHARJO RT48/05KARTOHARJO RT49/05KAUMANKERETA APIKKPH LAWU DSKKPH MADIUNKKPH SARADANKOLONEL MARHADIKRESNOKUTUK SENDANGLARASATILELELOMBOKMARGATAMAMODIN KARTOHARJOMUJAIRNGUPASANONTOSENOPAHLAWANPAHLAWAN 4PAHLAWAN GG RUSDIKAPAHLAWAN R-DOCPAHLAWAN R-INFOMEDIA OSTSPAHLAWAN R-LOKER OSTSPAHLAWAN R-MAN INFOMEDIA OSTSPAHLAWAN R-SISFO LAMAPAHLAWAN R-UPIM OSTSPAHLAWAN R-UPMB OSTSPANCAWALAPANCAWALA 1PANCAWALA 2PANGLIMA SUDIRMANPARIKESITPASAR BESARPASAR BUNGAPENITIPAN SEPEDAPERENCANAAN PERHUTANIPERHUTANI DALAMPERINTIS KEMERDEKAANPERINTIS KEMERDEKAAN 1PERINTIS KEMERDEKAAN 2PERINTIS KEMERDEKAAN 3PERINTIS KEMERDEKAAN 4PERINTIS KEMERDEKAAN 5PERUM BUMI ANTARIKSAPOLRIPRAJANPURBAJAYAPUSDIK PERHUTANIPUTRAREL KERETARIMBA DARMARIMBA JAYARIMBA KAYARIMBA MULYARIMBA RAYARSU MERPATISASONO MULYOSDSD PETRASDN 1,2,4 KARTOHARJOSDN KARTOHARJO 3,4,5SENDANGSENDANG 1SENDANG 2SENDANG 3SENDANG BARATSENDANG GAYAMSENDANG KULONSENDANG TIMURSENDANG TOMBROSERAMSLAMET RIYADISLTP TAMAN DEWASASMEA TAMAN DEWASASMU COKROAMINOTOSMU TAMAN BAKTISMU TAMAN SISWASOSRODIPRAJANSRI KALOKOSRI LINUHUNGSRI WIBOWOSRISEDANISTMSULAWESISULAWESI 1SUMBAWASUMBER UMISSUNAN MALIK IBRAHIMTAWANG SARITIMBUL JAYA MALL BLOK ....TIMORTPK(TEMPAT PENAMPUNGAN KAYU)UDOWOUDOYO 1WIYATA JAYAXXXX</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;street&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='street']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/section[2]/form/div[3]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Terdekat'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KECAMATAN'])[1]/following::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Jalan'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Lengkap'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
   </webElementXpaths>
</WebElementEntity>
